import os
import feedparser
import requests
from datetime import datetime
import markdown2
from weasyprint import HTML
from bs4 import BeautifulSoup

# === BETTER RSS SOURCES (verified as of June 2026) ===
COMPANIES = {
    "OpenAI": "https://openai.com/news/rss.xml",
    "Anthropic": "https://raw.githubusercontent.com/Olshansk/rss-feeds/main/feeds/feed_anthropic_news.xml",
    "Google DeepMind": "https://deepmind.google/blog/rss.xml",
    "Microsoft AI": "https://news.microsoft.com/source/topics/ai/feed/",
    "xAI Grok": "https://raw.githubusercontent.com/Olshansk/rss-feeds/main/feeds/feed_xainews.xml",  # Community-generated (reliable)
    "DeepSeek": "https://huggingface.co/blog/feed.xml",  # Fallback + monitor their announcements
    "Alibaba Qwen": "https://qwenlm.github.io/blog/feed.xml",
    "Meta Llama": "https://ai.meta.com/blog/feed/",  # Or use RSSHub if needed
}

# Use Grok API (fast & good for summarization)
from grokapi import Grok   # pip install grokapi

client = Grok(api_key=os.getenv("GROK_API_KEY"))

def get_latest_news(company, url):
    try:
        feed = feedparser.parse(url)
        if not feed.entries:
            return f"**{company}**: No major updates in the last 24h."
        
        entry = feed.entries[0]
        prompt = f"""
        Create a crisp 1-2 line summary for a daily AI newsletter about this update from {company}.
        Include model name / key feature if any. Be factual and neutral.
        Title: {entry.title}
        Description: {entry.description[:700] if 'description' in entry else ''}
        Link: {entry.link}
        """
        response = client.chat.completions.create(
            model="grok-3",
            messages=[{"role": "user", "content": prompt}]
        )
        summary = response.choices[0].message.content.strip()
        return f"**{company}**: {summary}\nSource: [{entry.title}]({entry.link})"
    
    except Exception:
        return f"**{company}**: No major updates today."

# === GENERATE CONTENT ===
today = datetime.now().strftime("%Y-%m-%d")
md_content = f"# Daily AI Updates from Top Companies\n**Date:** {today} (Weekday)\n\n"

for company, url in COMPANIES.items():
    summary = get_latest_news(company, url)
    md_content += f"{summary}\n\n"

md_content += "\n---\nAuto-generated by GitHub Actions • [View all archives](https://github.com/YOUR-USERNAME/daily-ai-updates/tree/main/summaries)"

# Save Markdown
os.makedirs("summaries", exist_ok=True)
with open(f"summaries/{today}.md", "w", encoding="utf-8") as f:
    f.write(md_content)

# Generate PDF
os.makedirs("pdfs", exist_ok=True)
html_content = markdown2.markdown(md_content, extras=["tables", "fenced-code-blocks"])
HTML(string=html_content).write_pdf(f"pdfs/{today}.pdf")

print(f"✅ Daily summary generated for {today}")
